image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

before_script:
  - apk add --no-cache curl bash jq sshpass

variables:
  DOCKER_DRIVER: overlay2
  SSH_USER: "root"
  SSH_SERVER: "92.53.105.243"  # IP или домен вашего сервера
  SSH_PASSWORD: "nb-*vioWTyK4K?"
  CI_REGISTRY_USER: "$CI_REGISTRY_USER"
  CI_REGISTRY_PASSWORD: "$CI_REGISTRY_PASSWORD"
  CI_REGISTRY: "$CI_REGISTRY"


build:
  stage: build
  script:
    - echo "Сборка Docker образа"
    - echo "$CI_REGISTRY_IMAGE:latest"
    - docker build -t $CI_REGISTRY_IMAGE/s3-storage:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/s3-storage:latest
  artifacts:
    paths:
      - build/
  parallel:
    matrix:
      - TEST: "test"

test:
  image: golang:1.22-alpine
  stage: test
  services:
    - name: mongodb/mongodb-community-server:6.0-ubi8
      alias: mongodb  # Это важно для обращения к MongoDB в тестах
  variables:
    MONGO_INITDB_ROOT_USERNAME: user
    MONGO_INITDB_ROOT_PASSWORD: password
  script:
    - echo "Запуск тестовой MongoDB"
    - sleep 10  # Даем время для запуска MongoDB
    - echo "Запуск юнит-тестов"
    - go test ./...
  after_script:
    - echo "Удаление тестовой базы MongoDB"

deploy:
 stage: deploy
 only:
   - master
 before_script:
   - apk add --no-cache openssh sshpass
 script:
   - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_SERVER" '
       echo '"$CI_REGISTRY_PASSWORD"' | docker login --username '"$CI_REGISTRY_USER"' --password-stdin '"$CI_REGISTRY"' &&
       cd /root/compose-env &&
       docker compose pull &&
       docker compose up -d --no-build
     '

